language: ruby
sudo: true
before_install:
  - gem update bundler

rvm:
#  - 1.9.3	
#  - 2.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0

gemfile:
  - Gemfile

install:
  - bundle exec rake build
  - sudo fluent-gem install --local pkg/fluent-plugin-ufw-0.0.1.gem
